### ISSUE TITLE
Docker container keeps crashing after check-in

### ISSUE THREAD

**Issue by muitenphale** [Bing-su/genshin-auto-daily-check-in-docker#3]
Check-in rewards are still received but container keeps crashing. Please see the container log in attached file.
[Crash log.txt](https://github.com/user-attachments/files/17356614/Crash.log.txt)

**Comment by muitenphale** [comment]
Also adding **ltmid_v2** by the end of ACCOUNT1 or ACCOUNT2 will cause crash immediately. I can only use **ltuid_v2** and **ltoken_v2**

**Comment by Bing-su** [comment]
ㄳㄳ 업데이트했습니다
